name: tests

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install libreoffice
        run: sudo apt update && sudo apt-get install -y libreoffice
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build and test REST example
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :samples:spring-boot-rest:test
      - name: Report
        uses: dorny/test-reporter@v1.6.0
        if: always()
        with:
          name: Tests Results REST
          path: "samples/spring-boot-rest/**/test-results/**/TEST*.xml"
          reporter: java-junit
          fail-on-error: false
      - name: Build and test WEBAPP example
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :samples:spring-boot-rest:test
      - name: Report
        uses: dorny/test-reporter@v1.6.0
        if: always()
        with:
          name: Tests Results WEBAPP
          path: "samples/spring-boot-webapp/**/test-results/**/TEST*.xml"
          reporter: java-junit
          fail-on-error: false
      - name: Build and Basic WebApp
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :samples:basic-webapp:build
